[package]
name = "fmt"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
eyre = "0.6.12"
prettytable = "0.10.0"
textwrap = "0.16.1"
unicode-width = "0.2.0"
